import { Knex } from 'knex';

import { Util } from '../../util';

import { ETableNames } from '../eTableNames';

const padroesNfse = [
  { id: 1, nome: 'Padrão Ábaco' },
  { id: 2, nome: 'Padrão DSFNET' },
  { id: 3, nome: 'Padrão E-Nota Portal Público' },
  { id: 4, nome: 'Padrão E&L' },
  { id: 5, nome: 'Padrão ISSNET' },
  { id: 6, nome: 'Padrão Lençóis Paulista' },
  { id: 7, nome: 'Padrão SIGCORP Londrina' },
  { id: 8, nome: 'Padrão E-Caucaia' },
  { id: 9, nome: 'Padrão Freire' },
  { id: 10, nome: 'Padrão NFWEB' },
  { id: 11, nome: 'Padrão ISSWEB Fiorilli' },
  { id: 12, nome: 'Padrão Cecam' },
  { id: 13, nome: 'Padrão Goiânia' },
  { id: 14, nome: 'Padrão SIGCORP – TXT' },
  { id: 15, nome: 'Padrão GINFES' },
  { id: 16, nome: 'Padrão BOANF' },
  { id: 17, nome: 'Padrão BETHA' },
  { id: 18, nome: 'Padrão PRODATA' },
  { id: 19, nome: 'Padrão SimplISS' },
  { id: 20, nome: 'Padrão ISSWEB Camaçari' },
  { id: 21, nome: 'Padrão SMARAPD SIL Tecnologia WS' },
  { id: 22, nome: 'Padrão Dueto' },
  { id: 23, nome: 'Padrão IPM' },
  { id: 24, nome: 'Padrão WEB ISS' },
  { id: 25, nome: 'Padrão NF-em' },
  { id: 26, nome: 'Padrão Nota Blu' },
  { id: 27, nome: 'Padrão Lexsom' },
  { id: 28, nome: 'Padrão eISS' },
  { id: 29, nome: 'Padrão Nota Natalense' },
  { id: 30, nome: 'Padrão Equiplano' },
  { id: 31, nome: 'Padrão FacilitaISS' },
  { id: 32, nome: 'Padrão SEMFAZ' },
  { id: 33, nome: 'Padrão Tecnos' },
  { id: 34, nome: 'Padrão SIGCORP Rio Grande' },
  { id: 35, nome: 'Padrão INFISC – Santiago' },
  { id: 36, nome: 'Padrão INFISC – Sapucaia' },
  { id: 37, nome: 'Padrão Governo Digital' },
  { id: 38, nome: 'Padrão Governa TXT' },
  { id: 39, nome: 'Padrão e-Receita' },
  { id: 40, nome: 'Padrão SIGCORP São Gonçalo' },
  { id: 41, nome: 'Padrão ArrecadaNet' },
  { id: 42, nome: 'Padrão RLZ' },
  { id: 43, nome: 'Padrão PMJP' },
  { id: 44, nome: 'Padrão Governo Eletrônico' },
  { id: 45, nome: 'Padrão PortalFacil' },
  { id: 46, nome: 'Padrão ISS On-line Supernova' },
  { id: 47, nome: 'Padrão ISSNFe On-line' },
  { id: 48, nome: 'Padrão DEISS' },
  { id: 49, nome: 'Padrão SIGCORP Ivaipora' },
  { id: 50, nome: 'Padrão SAPITUR' },
  { id: 51, nome: 'Padrão ISS Fortaleza' },
  { id: 52, nome: 'Padrão Metrópolis' },
  { id: 53, nome: 'Padrão Consist' },
  { id: 54, nome: 'Padrão Tributos Municipais' },
  { id: 55, nome: 'Padrão SIGCORP Cianorte' },
  { id: 56, nome: 'Padrão INFISC Garibaldi' },
  { id: 57, nome: 'Padrão INFISC Campo Bom' },
  { id: 58, nome: 'Padrão Siappa' },
  { id: 59, nome: 'Padrão Janela Única' },
  { id: 60, nome: 'Padrão Obaratech' },
  { id: 61, nome: 'Padrão Mitra' },
  { id: 62, nome: 'Padrão WEB ISS 2.0' },
  { id: 63, nome: 'Padrão 3enet' },
  { id: 64, nome: 'Padrão SigCORP Marília' },
  { id: 65, nome: 'Padrão Asten' },
  { id: 66, nome: 'Padrão NFPSe WS' },
  { id: 67, nome: 'Padrão SIGCORP Itapira' },
  { id: 68, nome: 'Padrão SigCorp Botucatu' },
  { id: 69, nome: 'Padrão SIGCorp Sarandi' },
  { id: 70, nome: 'Padrão SIGCorp Petrópolis' },
  { id: 71, nome: 'Padrão 3TECNOS Upload XML' },
  { id: 72, nome: 'Padrão Città' },
  { id: 73, nome: 'Padrão VLCNET WS' },
  { id: 74, nome: 'Padrão D2TI' },
  { id: 75, nome: 'Padrão E-Nota WS' },
  { id: 76, nome: 'Padrão RLZ ABRASF' },
  { id: 77, nome: 'Padrão Prefeitura Rápida' },
  { id: 78, nome: 'Padrão INFISC CFS-e' },
  { id: 79, nome: 'Padrão N&A Informática' },
  { id: 80, nome: 'Padrão GLC Consultoria WS' },
  { id: 81, nome: 'Padrão CENTI 2' },
  { id: 82, nome: 'Padrão Prescon WS' },
  { id: 83, nome: 'Padrão ENota Fiscal' },
  { id: 84, nome: 'Padrão Gefisco 2' },
  { id: 85, nome: 'Padrão NFSeWeb' },
  { id: 86, nome: 'Padrão Futurize' },
  { id: 87, nome: 'Padrão Barueri' },
  { id: 88, nome: 'Padrão Ativ' },
  { id: 89, nome: 'Padrão E-Ticons' },
  { id: 90, nome: 'Padrão Tributos Municipais WS' },
  { id: 91, nome: 'Padrão FINTELISS' },
  { id: 92, nome: 'Padrão FGMAISS' },
  { id: 93, nome: 'Padrão AWATAR' },
  { id: 94, nome: 'Padrão GLC Consultoria (Sumaré e Monte Mor)' },
  { id: 95, nome: 'Padrão Thema' },
  { id: 96, nome: 'Padrão GENERATIVA' },
  { id: 97, nome: 'Padrão ISSE' },
  { id: 98, nome: 'Padrão SMARAPD SIL Tecnologia' },
  { id: 99, nome: 'Padrão Nota Carioca' },
  { id: 100, nome: 'Padrão JFISS Digital' },
  { id: 101, nome: 'Padrão ISISS' },
  { id: 102, nome: 'Padrão Elotech' },
  { id: 103, nome: 'Padrão NF Paulistana' },
  { id: 104, nome: 'Padrão NFSeNET' },
  { id: 105, nome: 'Padrão INFISC – Caxias do Sul' },
  { id: 106, nome: 'Padrão Pública' },
  { id: 107, nome: 'Padrão Assessor Público' },
  { id: 108, nome: 'Padrão NFPSe' },
  { id: 109, nome: 'Padrão Ágili' },
  { id: 110, nome: 'Padrão Nota Salvador' },
  { id: 111, nome: 'Padrão ISS Intel' },
  { id: 112, nome: 'Padrão TIPLAN' },
  { id: 113, nome: 'Padrão Solução Pública' },
  { id: 114, nome: 'Padrão DB NFSE' },
  { id: 115, nome: 'Padrão DigiFred' },
  { id: 116, nome: 'Padrão BSIT-BR' },
  { id: 117, nome: 'Padrão FISS-LEX' },
  { id: 118, nome: 'Padrão SJP' },
  { id: 119, nome: 'Padrão Tinus' },
  { id: 120, nome: 'Padrão SH3' },
  { id: 121, nome: 'Padrão Governa' },
  { id: 122, nome: 'Padrão Prescon' },
  { id: 123, nome: 'Padrão Tinus Upload' },
  { id: 124, nome: 'Padrão CONAM' },
  { id: 125, nome: 'Padrão Comunix' },
  { id: 126, nome: 'Padrão e-Governe ISS' },
  { id: 127, nome: 'Padrão NF-Eletronica' },
  { id: 128, nome: 'Padrão Memory' },
  { id: 129, nome: 'Padrão System' },
  { id: 130, nome: 'Padrão ISS Online AEG' },
  { id: 131, nome: 'Padrão ISS Simples SPCONSIG' },
  { id: 132, nome: 'Padrão SAATRI' },
  { id: 133, nome: 'Padrão INFISC Farroupilha' },
  { id: 134, nome: 'Padrão SIAM' },
  { id: 135, nome: 'Padrão NFSE-ECIDADES' },
  { id: 136, nome: 'Padrão DUETO 2.0' },
  { id: 137, nome: 'Padrão CENTI' },
  { id: 138, nome: 'Padrão COPLAN' },
  { id: 139, nome: 'Padrão SISNFe BAURU' },
  { id: 140, nome: 'Padrão JGBAIAO' },
  { id: 141, nome: 'Padrão Primax Online' },
  { id: 142, nome: 'Padrão VLCNET' },
  { id: 143, nome: 'Padrão GENFE' },
  { id: 144, nome: 'Padrão SysISS' },
  { id: 145, nome: 'Padrão NF Eletrônica 2.0' },
  { id: 146, nome: 'Padrão Betha 2.0' },
  { id: 147, nome: 'Padrão GESPAM' },
  { id: 148, nome: 'Padrão SIGCORP MOGI GUAÇU' },
  { id: 149, nome: 'Padrão DATAPUBLIC' },
  { id: 150, nome: 'Padrão ISANETO' },
  { id: 151, nome: 'Padrão Sigcorp São João de Meriti' },
  { id: 152, nome: 'Padrão NFSD' },
  { id: 153, nome: 'Padrão Embras Siap.Net' },
  { id: 154, nome: 'Padrão GIAP' },
  { id: 155, nome: 'Padrão SMARAPDSil WS2' },
  { id: 156, nome: 'Padrão SigCORP Governador Valadares' },
  { id: 157, nome: 'Padrão Tiplan 2.0' },
  { id: 158, nome: 'Padrão DEISS WS' },
  { id: 159, nome: 'Padrão INFISC Bom Princípio' },
  { id: 160, nome: 'Padrão SafeWeb' },
  { id: 161, nome: 'Padrão SIAP' },
  { id: 162, nome: 'Padrão ASPEC' },
  { id: 163, nome: 'Padrão Awatar WS' },
  { id: 164, nome: 'Padrão NF-em Joinville' },
  { id: 165, nome: 'Padrão Sigcorp Abrasf' },
  { id: 166, nome: 'Padrão DSF 1' },
  { id: 167, nome: 'Padrão H2M Soluções' },
  { id: 168, nome: 'Padrão Gefisco' },
  { id: 169, nome: 'Padrão SISGENFe' },
  { id: 170, nome: 'Padrão Public Soft' },
  { id: 171, nome: 'Padrão ISS.MAP' },
  { id: 172, nome: 'Padrão ADM Nota Fiscal' },
  { id: 173, nome: 'Padrão Ágape' },
  { id: 174, nome: 'Padrão Município Eletrônico' },
  { id: 175, nome: 'Padrão Tchê Informática' },
  { id: 176, nome: 'Padrão Bauhaus' },
  { id: 177, nome: 'Padrão NFServiço' },
  { id: 178, nome: 'Padrão Belga NFSe' },
  { id: 179, nome: 'Padrão SS Informática' },
  { id: 180, nome: 'Padrão XTROnline' },
  { id: 181, nome: 'Padrão Elmar Tecnologia' },
  { id: 182, nome: 'Padrão Kalana' },
  { id: 183, nome: 'Padrao NFE-HD' },
  { id: 184, nome: 'Padrão Caucaia – WS' },
  { id: 185, nome: 'Padrão EBM Informática' },
  { id: 186, nome: 'Padrão Datapublic Webservice' },
  { id: 187, nome: 'Padrão Horus ISS' },
];

export async function up(knex: Knex): Promise<void> {
  await knex(ETableNames.nfse_padroes)
    .insert(padroesNfse.map((p) => ({ id: p.id, nome: p.nome, ativo: true })))
    .then(() => {
      Util.Log.info(`# Inseridos ${padroesNfse.length} registros na tabela ${ETableNames.nfse_padroes}`);
    });
}

export async function down(knex: Knex): Promise<void> {
  await knex(ETableNames.nfse_padroes)
    .whereIn(
      'id',
      padroesNfse.map((p) => p.id),
    )
    .del()
    .then(() => {
      Util.Log.info(`# Removidos ${padroesNfse.length} registros da tabela ${ETableNames.nfse_padroes}`);
    });
}
